runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/(mapreduce|queue|warmup).*  
  script: mysite.wsgi.application
  login: admin

- url: /static
  static_dir: static/

- url: /.*
  script: mysite.wsgi.application


# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK 
# Using Third Party Libraries: https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27
libraries:
- name: MySQLdb
  version: 1.2.5
# Wagtail needs specific PIL version which should not collide with version in lib/
- name: PIL
  version: "1.1.7"

# Google App Engine limits application deployments to 10,000 uploaded files per
# version. The skip_files section allows us to skip virtual environment files
# to meet this requirement. The first 5 are the default regular expressions to
# skip, while the last one is for all env/ files.
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^vnv/.*$
- ^(lib/PIL*)
- ^(lib/google_appengine*)
- .*egg-info/*.*
- .*dist-info/*.*



# env.yaml has 'env_variable' section with environment variables
# that need to be set prior to deployment.
includes:
- env.yaml
